### ISSUE TITLE
[DOC] improve docs for miss_hit

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/.github#3]
`miss_hit` is constantly updated and the CI will download the latest version. If a user is using locally an older version, might not solve eg style issues flagged by CI.

Add a reminder to locally upgrade regularly `miss_hit`.

How to be notified when a new release of `miss_hit` is out? Go to (miss_hit repo)[https://github.com/florianschanda/miss_hit], click on `watch` (up-right corner), and set notification for new releases.

**Comment by Remi-Gau** [comment]
Maybe we should also "lock" the package version in the continuous integration so that the version bump is under our control

**Comment by marcobarilari** [comment]
yes, this is probably a smarter solution

**Comment by Remi-Gau** [comment]
I actually set the version in the `requirements.txt` file of each repo and I am letting the CI read the version of miss_hit to install from there.

This also means that after creating a virtual env, doing `pip install -r requirements` will make sure that everyone works with the same stuff.
